accounts:
  - name: hung
    coins: ["900000token", "200000000stake"]
  - name: minh
    coins: ["100000token", "100000000stake"]
  - name: long
    coins: ["100000token"]
validator:
  name: hung
  staked: "200000000stake"
  
  name: "minh"
  staked: "100000000stake"

client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: long
  coins: ["10token", "100000stake"]
